[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
uefi = { version = "0.33.0", features = ["logger", "panic_handler"] }

[[bin]]
name = "bootloader"
path = "main.rs"

[toolchain]
targets = ["aarch64-unknown-uefi", "i686-unknown-uefi", "x86_64-unknown-uefi"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
